gpt:
  name: gpt
  n_votes: 1
  temperature: 0
  model: gpt-3.5-turbo-0125
  max_tries: 1
  frequency_penalty: 0
  presence_penalty: 0
  max_tokens: 1000


oai_embed:
  name: openai_embedding
  model: text-embedding-3-large


dataset:
  data_path: 'data'
  split: ''
  max_samples: 100
  batch_size: 20
  start_sample: 0


save: True
save_new_results: True
results_dir: ./results/
use_cache: True
clear_cache: False
use_cached_codex: False
cached_codex_path: ''
log_every: 10
wandb: True


blip_half_precision: True
blip_v2_model_type: blip2-flan-t5-xxl
